### ISSUE TITLE
Disabled vtex-io/build in cy-runner

### ISSUE THREAD

**Issue by Syed-Vtex** [vtex-apps/cy-runner#9]
<img width="943" alt="Screen Shot 2022-03-22 at 1 00 06 PM" src="https://user-images.githubusercontent.com/92449902/159429826-9cebf692-1557-4f1b-b5a6-83eab6f1cda4.png">

**Comment by thyarles** [comment]
Thanks for bringing this to here, Syed. I asked the team, bot no answer so far. I'll ping them again.
